// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epiiamkvbyudknjgkohm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwaWlhbWt2Ynl1ZGtuamdrb2htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjY2ODUsImV4cCI6MjA2MjIwMjY4NX0.1KO8MNRBG3-AR6O_vZjeofKi_Uikj81sQn8X18XeVv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);